import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "zod";

/**
 * Content is generated by `npm run extract` from the cached WordPress site.
 * Do not hand-edit `src/content/pages/*.json` - the next extraction run
 * overwrites it (wp-migration M-EXTRACT-GENERATED).
 *
 * A block carries both its content and the Tailwind classes compiled from the
 * old site's Oxygen CSS, so the schema is recursive and deliberately loose
 * about which visual fields are present on which kind.
 */
const block: z.ZodType<unknown> = z.lazy(() =>
  z.object({
    kind: z.enum([
      "section",
      "columns",
      "div",
      "heading",
      "richtext",
      "button",
      "link",
      "image",
      "html",
      "group",
      "text",
      "form",
      "navmenu",
      "tabs",
      "spectable",
    ]),
    id: z.string().optional(),
    className: z.string().optional(),
    isCard: z.boolean().optional(),
    wrapClassName: z.string().optional(),
    bg: z
      .object({ layers: z.array(z.string()) })
      .nullable()
      .optional(),
    bgSize: z.string().nullable().optional(),
    bgPosition: z.string().nullable().optional(),
    // kind-specific
    level: z.number().optional(),
    html: z.string().optional(),
    value: z.string().optional(),
    href: z.string().nullable().optional(),
    label: z.string().optional(),
    src: z.string().nullable().optional(),
    alt: z.string().optional(),
    width: z.string().nullable().optional(),
    height: z.string().nullable().optional(),
    tag: z.string().optional(),
    heading: z.string().optional(),
    intro: z.string().optional(),
    unresolved: z.boolean().optional(),
    table: z.string().optional(),
    items: z
      .array(z.object({ label: z.string(), href: z.string().nullable(), current: z.boolean() }))
      .optional(),
    tabs: z
      .array(
        z.object({
          id: z.string(),
          label: z.string(),
          className: z.string().optional(),
          innerId: z.string().optional(),
          innerClassName: z.string().optional(),
        }),
      )
      .optional(),
    panels: z.array(z.object({ id: z.string(), children: z.array(block) })).optional(),
    children: z.array(block).optional(),
  }),
);

const pages = defineCollection({
  loader: glob({ pattern: "*.json", base: "./src/content/pages" }),
  schema: z.object({
    slug: z.string(),
    wpId: z.number().nullable(),
    path: z.string(),
    title: z.string(),
    description: z.string(),
    ogImage: z.string().nullable(),
    sections: z.array(block),
    template: z.string().optional(),
    // Every page, grouped by the extractor into the shape the templates
    // render: a header, a lead whose opening paragraph is the standfirst, then
    // one section per h2 with its h3s as items.
    doc: z
      .object({
        key: z.string(),
        title: z.string(),
        eyebrow: z.string(),
        eyebrowHref: z.string().nullable(),
        heroImage: z.string().nullable(),
        supportImage: z.string().nullable(),
        lead: z.object({
          headline: z.string().nullable(),
          hero: z.string(),
          body: z.array(block),
        }),
        sections: z.array(
          z.object({
            id: z.string(),
            headline: z.string(),
            body: z.array(block),
            items: z.array(z.object({ headline: z.string(), body: z.array(block) })),
          }),
        ),
        nav: z
          .object({
            heading: z.string().optional(),
            items: z.array(
              z.object({ label: z.string(), href: z.string().nullable(), current: z.boolean() }),
            ),
          })
          .nullable(),
      })
      .optional(),
  }),
});

export const collections = { pages };
